libs = io

io_sources = src/io.cpp
io_export_includes = include
io_libraries = libcommon.so

tua-tests = tests/io_task.cpp tests/io_loop.cpp tests/io_buf.cpp tests/io_sock_addr.cpp tests/io_net.cpp tests/io_loop_more.cpp
tests_io_task_libraries = libio.so
tests_io_loop_libraries = libio.so
tests_io_buf_libraries = libio.so
tests_io_sock_addr_libraries = libio.so
tests_io_net_libraries = libio.so
tests_io_loop_more_libraries = libio.so